myEcommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("",include("web.urls")),
    path('admin/', admin.site.urls),
    path('paypal/', include("paypal.standard.ipn.urls")),

] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/urls.py
from django.urls import path
from . import views

app_name = "web"
urlpatterns = [
    path('',views.index, name="index"),
    path("productsByCategory/<int:category_id>", views.productsByCategory, name="productsByCategory"),
    path("productsByName", views.productsByName, name="productsByName"),
    path("product/<int:product_id>", views.productDetail, name="product"),
    path("car", views.car, name="car"),
    path("addToCar/<int:product_id>", views.addToCar, name="addToCar"),
    path("deleteProductToCar/<int:product_id>", views.deleteProductToCar, name="deleteProductToCar"),
    path("clearCar", views.clearCar, name="clearCar"),
    path("createUser", views.createUser, name="createUser") ,
    path("acount", views.userAcount, name="acount"),
    path("updateClient", views.updateClient, name="updateClient"),
    path("login", views.loginUser, name="loginUser"),
    path("logout", views.logoutUser, name="logoutUser"),
    path("registerOrder", views.registerOrder, name="registerOrder"),
    path("confirmOrder", views.confirmOrder, name="confirmOrder"),
    path("thanks", views.thanks, name="thanks")
]

web/templates/includes/footer.html
{% load static %}
<!--footer-->
    <div class="container-fluid blog-sb-widgets page-styling site-footer">
        <div class="row">
            <div class="col-sm-12 col-md-4 widget align-center-tablet f-logo-wrap">
                <a href="index.html" class="f-logo">
                    <img src="{% static 'img/logo.png' %}" alt="">
                </a>
                <p>Proyecto Ecommerce con Django para EdTeam</p>
                <button class="btn callback">Contacto</button>
            </div>
        </div>
    </div>

web/templates/includes/header.html
{% load static %}
    <!--header-->
    <div class="site-header">

        <p class="h-logo">
            <a href="/"><img src="{% static 'img/logo.png' %}" alt="EdShop"></a>
        </p><!--
    No Space
    --><div class="h-shop">

        <form method="post" action="{% url 'web:productsByName' %}" class="h-search" id="h-search">
            {% csrf_token %}
            <input type="text" name="name" placeholder="Search...">
            <button type="submit"><i class="ion-search"></i></button>
        </form>

        <ul class="h-shop-links">
            <li class="h-search-btn" id="h-search-btn"><i class="ion-search"></i></li>
            
            <li class="h-shop-icon h-profile">
                <a href="auth.html" title="My Account">
                    <i class="ion-android-person"></i>
                </a>
                <ul class="h-profile-links">
                    <li><a href="/login">Login / Registro</a></li>
                    <li><a href="/logout">Logout</a></li>
                </ul>
            </li>
            {% include 'includes/header_carrito.html' %}
        </ul>
    </div></div>

web/templates/includes/header_carrito.html
<li class="h-cart">
    <a class="cart-contents" href="car.html">
        <p class="h-cart-icon">
            <i class="ion-android-cart"></i>
            <span>{{request.session.car.items|length}}</span>
        </p>
        <p class="h-cart-total">${{request.session.carTotal}}</p>
    </a>
    <div class="widget_shopping_cart">
        <div class="widget_shopping_cart_content">
            <ul class="car_list">
                {% for key,value in request.session.car.items %}
                <li>
                    <a href="{% url 'web:deleteProductToCar' value.product_id %}" class="remove">&times;</a>
                    <a href="#">
                        <img src="{{value.image}}" alt="">
                        {{value.name}}
                    </a>
                    <span class="quantity">{{value.cuantity}} &times; ${{value.total}}</span>
                </li>
                {% endfor %}
            </ul>
            <p class="total"><b>Total:</b>${{request.session.carTotal}}</p>
            <p class="buttons">
                <a href="{% url 'web:car' %}" class="button">Ver Carrito</a>
                <a href="#" class="button">Pedido</a>
            </p>
        </div>
    </div>
</li>

web/templates/includes/navbar.html
<!--navbar-->
<div class="container-fluid page-styling site-header-before">
    <div class="row">
        <div class="col-lg-4">
            <ul class="links_list links_list-align-left align-center-desktop topbar-social">
                <li>
                    <p class="links_list-value">
                        <a href="http://facebook.com" target="_blank" rel="nofollow">
                            <i class="fa fa-facebook"></i>
                        </a>
                    </p>
                </li>
            </ul>
        </div>
        <div class="col-lg-8">
            <ul class="links_list links_list-align-right align-center-desktop topbar-contacts">
                <li>
                    <p class="links_list-label">
                        Dirección
                    </p>
                    <p class="links_list-value">
                        <a href="http://maps.google.com" target="_blank" rel="nofollow">Calle 123,Lima Perú</a>
                    </p>
                </li>
                <li>
                    <p class="links_list-label">
                        Contacto
                    </p>
                    <p class="links_list-value">
                        <a href="mailto:support@email.com">Support@Email.com</a>
                    </p>
                </li>
                <li>
                    <p class="links_list-label">
                        Telefono
                    </p>
                    <p class="links_list-value">
                        <a href="tel:4785929899">(478)-592-9899</a>
                    </p>
                </li>
            </ul>
        </div>
    </div>
</div>