myEcommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("",include("web.urls")),
    path('admin/', admin.site.urls),
    path('paypal/', include("paypal.standard.ipn.urls")),

] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/urls.py
from django.urls import path
from . import views

app_name = "web"
urlpatterns = [
    path('',views.index, name="index"),
    path("productsByCategory/<int:category_id>", views.productsByCategory, name="productsByCategory"),
    path("productsByName", views.productsByName, name="productsByName"),
    path("product/<int:product_id>", views.productDetail, name="product"),
    path("car", views.car, name="car"),
    path("addToCar/<int:product_id>", views.addToCar, name="addToCar"),
    path("deleteProductToCar/<int:product_id>", views.deleteProductToCar, name="deleteProductToCar"),
    path("clearCar", views.clearCar, name="clearCar"),
    path("createUser", views.createUser, name="createUser") ,
    path("acount", views.userAcount, name="acount"),
    path("updateClient", views.updateClient, name="updateClient"),
    path("login", views.loginUser, name="loginUser"),
    path("logout", views.logoutUser, name="logoutUser"),
    path("registerOrder", views.registerOrder, name="registerOrder"),
    path("confirmOrder", views.confirmOrder, name="confirmOrder"),
    path("thanks", views.thanks, name="thanks")
]

web/models.py
from django.db import models

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=200)
    registration_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
    

class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.RESTRICT)
    name = models.CharField(max_length=200)
    description = models.TextField(null=True)
    price = models.DecimalField(max_digits=9, decimal_places=2)
    registration_date = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to="products", blank=True)

    def __str__(self):
        return self.name
    

from django.contrib.auth.models import User

class Client(models.Model): 
    user = models.OneToOneField(User, on_delete=models.RESTRICT)
    dni = models.CharField(max_length=10)
    gender = models.CharField(max_length=1, default="M")
    phone = models.CharField(max_length=20)
    birthdate = models.DateField(null=True)
    address = models.TextField() 

    def __str__(self):
        return self.dni


class Order(models.Model):

    state_choices = (
        ("0", "required"),
        ("1", "paid")
    )

    client = models.ForeignKey(Client, on_delete=models.RESTRICT)
    singup_date = models.DateTimeField(auto_now_add=True)
    number_order= models.CharField(max_length=20, null=True)
    total = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    state = models.CharField(max_length=1, default="0", choices= state_choices)


    def __str__(self):
        return self.number_order
    

class DetailOrder(models.Model):
    order = models.ForeignKey(Order, on_delete=models.RESTRICT)
    product = models.ForeignKey(Product, on_delete=models.RESTRICT)
    cuantity = models.IntegerField(default=1)
    subtotal = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.product.name

web/templates/car.html
{% extends 'layout.html' %}
{% block content %}
<h1 class="maincont-ttl">Car</h1>
    <ul class="b-crumbs">
        <li><a href="/">Home</a></li>
        <li>Car</li>
    </ul>
    <div class="page-styling">
    <div class="woocommerce prod-litems section-list">
        {% for key,value in request.session.car.items %}
            <article class="prod-li sectls">
                <div class="prod-li-inner">
                    <a href="product.html" class="prod-li-img">
                        <img src="{{value.image}}" alt="">
                    </a>
                    <div class="prod-li-cont">
                        <div class="prod-li-ttl-wrap">
                            <p>
                                <a href="#">{{value.category}}</a>
                            </p>
                            <h3><a href="product.html">{{value.name}}</a></h3>
                        </div><!--
                    No Space
                    -->
                        <div class="prod-li-prices">
                            <div class="prod-li-price-wrap">
                                <p>Precio</p>
                                <p class="prod-li-price">{{value.price}}</p>
                            </div>
                            <div class="prod-li-qnt-wrap">
                                <p class="qnt-wrap prod-li-qnt">
                                    <a href="#" class="qnt-plus prod-li-plus"><i class="icon ion-arrow-up-b"></i></a>
                                    <input type="text" value={{value.cuantity}}>
                                    <a href="#" class="qnt-minus prod-li-minus"><i class="icon ion-arrow-down-b"></i></a>
                                </p>
                            </div>
                            <div class="prod-li-total-wrap">
                                <p>Total</p>
                                <p class="prod-li-total">${{value.total}}</p>
                            </div>
                        </div><!--
                No Space
                -->
                    </div>
                    <div class="prod-li-info">
                        <div class="prod-li-rating-wrap">
                            <p data-rating="5" class="prod-li-rating">
                                <i class="rating-ico" title="1"></i><i class="rating-ico" title="2"></i><i class="rating-ico"
                                    title="3"></i><i class="rating-ico" title="4"></i><i class="rating-ico" title="5"></i>
                            </p>
                            <p class="prod-li-rating-count">12</p>
                        </div>
                        <p class="prod-li-add">
                            <a href="{% url "web:deleteProductToCar" value.product_id %}" class="button hover-label prod-addbtn"><i
                                    class="icon ion-close-round"></i><span>Eliminar</span></a>
                        </p>
                        <p class="prod-li-information">
                            <a href="#" class="hover-label"><i class="icon ion-more"></i><span>Show Information</span></a>
                        </p>
                    </div>
                </div>
            </article>
        {% endfor %}
    </div>
    <div class="cart-actions">
        <div class="coupon">
            <input type="text" placeholder="Coupon code">
            <input type="submit" class="button" value="Apply">
        </div>
        <div class="cart-collaterals">
            <a href="{% url "web:clearCar" %}" class="checkout-button button">Limpiar Carrito</a>
            <a href="{% url "web:registerOrder" %}" class="checkout-button button">Realizar Pedido</a>
            <div class="order-total">
                <p class="cart-totals-ttl">Total</p>
                <p class="cart-totals-val">${{request.session.carTotal}}</p>
            </div>
        </div>
    </div>


</div>

{% endblock %}

web/templates/compra.html
{% extends 'layout.html' %}
{% block content %}
<h1 class="maincont-ttl">Nro Order : {{order.number_order}}</h1>
    <ul class="b-crumbs">
        <li><a href="/">Home</a></li>
        <li>Order</li>
    </ul>
<div class="page-styling">
    <div class="woocommerce prod-litems section-list">
            <h2>Date : {{order.singup_date}}</h2>
            {%for detail in order.detailorder_set.all %}
            <article class="prod-li sectls">
                <div class="prod-li-inner">
                    <a href="#" class="prod-li-img">
                        <img src="" alt="">
                        <p>imagenes</p>
                    </a>
                    <div class="prod-li-cont">
                        <div class="prod-li-ttl-wrap">
                            <p>
                                <a href="#">{{detail.product.category}}</a>
                            </p>
                            <h3><a href="product.html">{{detail.product.name}}</a></h3>
                        </div>
                        <div class="prod-li-prices">
                            <div class="prod-li-price-wrap">
                                <p>Price</p>
                                <p class="prod-li-price">${{detail.product.price}}</p>
                            </div>
                        </div>
                        <div class="prod-li-qnt-wrap">
                            <p class="qnt-wrap prod-li-qnt">
                                <a href="#" class="qnt-plus prod-li-plus"><i class="icon ion-arrow-up-b"></i></a>
                                <input type="text" value="{{detail.cuantity}}">
                                <a href="#" class="qnt-minus prod-li-minus"><i class="icon ion-arrow-down-b"></i></a>
                            </p>
                        </div>
                        <div class="prod-li-total-wrap">
                            <p>Total</p>
                            <p class="prod-li-total">${{detail.subtotal}}</p>
                        </div>
                    </div>
                </div>
            </article>
            {% endfor %}
    </div>
    <div class="cart-actions">
            <div class="cart-collaterals">
                {{form.render}}
                <div class="order-total">
                    <p class="cart-totals-ttl">Total2</p>
                    <p class="cart-totals-val">${{order.total}}</p>
                </div>
            </div>
    </div>
</div>
{% endblock %}

web/templates/cuenta.html
{% extends 'layout.html' %}
{% block content %}
<h1 class="maincont-ttl">Bienvenido - {{user.username}}</h1>
    <ul class="b-crumbs">
        <li><a href="/">Home</a></li>
        <li>Mi Cuenta</li>
    </ul>    
    <article class="page-cont">
        <div class="page-styling">
            <div class="auth-wrap">
                <div class="auth-col">
                    <h2>Datos Personales</h2>
                    <form method="post" action="{% url 'web:updateClient' %}" class="register">
                        {% csrf_token %}
                        {{clientForm}}
                        <p class="auth-submit">
                            <input type="submit" value="Update">
                        </p>
                        <h2>{{menssage}}</h2>
                    </form>
                </div>
            </div>
        </div>
    </article>
{% endblock %}

web/templates/gracias.html
{% extends 'layout.html' %}
{% block content %}
<h1 class="maincont-ttl">Checkout OK</h1>
    <ul class="b-crumbs">
        <li><a href="index.html">Home</a></li>
        <li>Purchase</li>
    </ul>
    <h2>THANKS FOR YOUR PURCHASE</h2>
    <h3>Order Number : {{order.number_order}}</h3>
    <p>Te estaremos enviando un correo confirmando tu pedido</p>    
{% endblock %}

web/templates/index.html
{% extends 'layout.html' %}
{% block content %}
        <div class="section-top">

            <h1 class="maincont-ttl">Catalogo</h1>
            <ul class="b-crumbs">
                <li><a href="/">Inicio</a></li>
                <li>Catalogo</li>
            </ul>
        </div>
        <!-- To make Sidebar "Not Sticky" just remove  id="section-list-withsb" -->
        <div class="section-wrap-withsb">
            <aside class="blog-sb-widgets section-sb" id="section-sb">
                <div class="theiaStickySidebar">
                    <p class="section-filter-toggle filter_hidden">
                        <a href="#" id="section-filter-toggle-btn">Filtros</a>
                    </p>
                    <div class="section-filter">
                        <div class="section-filter">
                            {% include 'includes/catalogo/categorias.html' %}
                        </div>
                    </div>
                </div>
            </aside>        <div class="section-list-withsb" id="section-list-withsb">
            <div class="theiaStickySidebar">
                {% include 'includes/catalogo/catalogo.html' %}
            </div><!-- .theiaStickySidebar -->
        </div><!-- .section-list-withsb -->
        </div><!-- .section-wrap-withsb -->
{% endblock %}

web/templates/layout.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>EdShop</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="format-detection" content="telephone=no">

    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,900%7COpen+Sans:300,300i,400,400i,600,600i,700,700i&amp;subset=cyrillic" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.formstyler.css' %}">
    <link rel="stylesheet" href="{% static 'css/flexslider.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.fancybox.css' %}">
    <link rel="stylesheet" href="{% static 'css/ion.rangeSlider.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.mThumbnailScroller.css' %}">
    <link rel="stylesheet" href="{% static 'css/chosen.css' %}">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/elements.css' %}">
    <link rel="stylesheet" href="{% static 'css/media.css' %}">
    <link rel="stylesheet" href="{% static 'css/elements-media.css' %}">

</head>
<body>
<div id="page" class="site">
    
    {% include 'includes/navbar.html' %}

    {% include 'includes/header.html' %}        

    <div id="content" class="site-content">
        <div id="primary" class="content-area">
            <main id="main" class="site-main">
                <div class="cont maincont">
                    {% block content %}
                    {% endblock %}
                </div>
            </main><!-- #main -->
        </div><!-- #primary -->

    </div><!-- #content -->

   {% include 'includes/footer.html' %}
</div><!-- #page -->

<script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
<script src="{% static 'js/jquery-plugins.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>

</body>
</html>

web/templates/login.html
{% extends 'layout.html' %}
{% block content %}
    <h1 class="maincont-ttl">Registration / Login</h1>
    <ul class="b-crumbs">
        <li><a href="index.html">Home</a></li>
        <li>Registration & Login</li>
    </ul>
    <article class="page-cont">
        <div class="page-styling">
            <div class="auth-wrap">
                <div class="auth-col">
                    <h2>Sing In</h2>
                    <form method="post" class="login" action="{%  url 'web:loginUser' %}">
                        {% csrf_token %}   
                        <input type="hidden" name="destination" value="{{destination}}" />
                        <p> 
                            <label for="username">E-mail <span class="required">*</span></label>
                            <input type="text" id="username" name="user">
                        </p>
                        <p>
                            <label for="password">Password <span class="required">*</span></label>
                            <input type="password" id="password" name="password">
                        </p>
                        <p class="auth-submit">
                            <input type="submit" value="Login">
                            <input type="checkbox" id="rememberme" value="forever">
                            <label for="rememberme">Remember me</label>
                        </p>
                        <p>
                            <label for="alert-danger">{{error}}</label>
                        </p>
                    </form>
                </div>
                <div class="auth-col">
                    <h2>Sing Up</h2>
                    <form method="post" class="register" action="{% url 'web:createUser' %}">
                        {% csrf_token %}
                        <p>
                            <label for="reg_email">Email <span class="required">*</span></label>
                            <input type="email" id="reg_email" name="newUser">
                        </p>
                        <p>
                            <label for="reg_password">Password <span class="required">*</span></label>
                            <input type="password" id="reg_password" name="newPassword">
                        </p>
                        <p class="auth-submit">
                            <input type="submit" value="Crear Cuenta">
                        </p>
                    </form>
                </div>
            </div>
        </div>
    </article>

{% endblock %}

web/templates/payment.html
<h1>Show me the money!</h1>
<!-- writes out the form tag automatically -->
{{ form.render }}

web/templates/pedido.html
{% extends 'layout.html' %}
{% block content %}
<h1 class="maincont-ttl">REGISTRO DE PEDIDO</h1>
    <ul class="b-crumbs">
        <li><a href="/">Home</a></li>
        <li>pedido</li>
    </ul>
    <form method="post" action="{% url "web:confirmOrder" %}" class="register">
    {% csrf_token %}
    <article class="page-cont">
        <div class="page-styling">
            <div class="auth-wrap">
                <div class="auth-col">
                    <h2>Datos Personales</h2>
                    <p>
                        <label for="username">Nombres<span class="required">*</span></label>
                        {{clientForm.name}}
                    </p>
                    <p>
                        <label for="username">Apellidos<span class="required">*</span></label>
                        {{clientForm.last_name}}
                    </p>
                </div>
                <div class="auth-col">
                    <h2>Datos Envio</h2>
                    <p>
                        <label for="username">Telefono<span class="required">*</span></label>
                        {{clientForm.phone}}
                    </p>
                    <p>
                        <label for="username">Dirección<span class="required">*</span></label>
                        {{clientForm.address}}
                    </p>
                </div>
            </div>
        </div>
    </article>
    <article class="page-cont">
        <div class="page-styling">
            <h2>Confirmación de Productos</h2>
            <div class="woocommerce prod-litems section-list">
                {% for key,value in request.session.car.items %}
                <article class="prod-li sectls">
                    <div class="prod-li-inner">
                        <a href="#" class="prod-li-img">
                            <img src="{{ value.imagen }}" alt="">
                        </a>
                        <div class="prod-li-cont">
                            <div class="prod-li-ttl-wrap">
                                <p>
                                    <a href="#">value.categoria</a>
                                </p>
                                <h3><a href="product.html">{{ value.name }}</a></h3>
                            </div>
                            <div class="prod-li-prices">
                                <div class="prod-li-price-wrap">
                                    <p>Precio</p>
                                    <p class="prod-li-price">${{value.price}}</p>
                                </div>
                            </div>
                            <div class="prod-li-qnt-wrap">
                                <p class="qnt-wrap prod-li-qnt">
                                    <a href="#" class="qnt-plus prod-li-plus"><i class="icon ion-arrow-up-b"></i></a>
                                    <input type="text" value="{{value.cuantity}}">
                                    <a href="#" class="qnt-minus prod-li-minus"><i class="icon ion-arrow-down-b"></i></a>
                                </p>
                            </div>
                            <div class="prod-li-total-wrap">
                                <p>Total</p>
                                <p class="prod-li-total">${{value.total}}</p>
                            </div>
                        </div>
                    </div>
                </article>
                {% endfor %}
        </div>
        <div class="cart-actions">
                <div class="cart-collaterals">
                    <div class="order-total">
                        <p class="cart-totals-ttl">Total</p>
                        <p class="cart-totals-val">${{request.session.carTotal}}</p>
                    </div>
                </div>
        </div>
        </div>
    </article>
    <article class="page-cont">
        <div class="page-styling">
            <div class="auth-wrap">
                <div class="auth-col">
                    <p class="auth-submit">
                        <input type="submit" value="Confirmar Pedido">
                    </p>
            </div>
        </div>
    </article>
    </form>
{% endblock %}

web/templates/product.html
{% extends "layout.html" %}
{% block content %}
    <ul class= "b-crumbs">
        <li><a href="/">Home</a></li>
        <li><a href="/">Catalogue</a></li>
        <li>Product</li>
    </ul>
    <article>
        <div class="prod">
            <div class="prod-slider-wrap prod-slider-shown">
                <div class="flexslider prod-slider" id="prod-slider">
                    <ul class="slides">
                        <li>
                            <a date-fancybox-group="prod" class="fancy-img" href="#">
                                {% if product.image %}
                                    <img src="{{product.image.url}}" alt="">
                                {% else %}
                                    <img src="https://via.placeholder.com/250" alt="" >
                                {% endif %}
                            </a>
                        </li>
                        <li>
                            <a date-fancybox-group="prod" class="fancy-img" href="#">
                                {% if product.image %}
                                    <img src="{{product.image.url}}" alt="">
                                {% else %}
                                    <img src="https://via.placeholder.com/250" alt="" >
                                {% endif %}
                            </a>
                        </li>
                    </ul>
                    <div class="prod-slider-count">
                        <p>
                            <span class="count-cur">1</span> / <span class="count-all">2</span>
                        </p>
                        <p class="hover-label prod-slider-zoom">
                            <i class= "icon ion-search"></i><span>Zoom In</span>
                        </p>
                    </div>
                </div>
                <divclass="flexslider prod-thumbs" id="prod-thumbs">
                    <ul class="slides">
                        <li>
                            {% if product.image %}
                                    <img src="{{product.image.url}}" alt="">
                                {% else %}
                                    <img src="https://via.placeholder.com/250" alt="">
                                {% endif %}
                        </li>
                        <li>
                            {% if product.image %}
                                    <img src="{{product.image.url}}" alt="">
                                {% else %}
                                    <img src="https://via.placeholder.com/250" alt="">
                                {% endif %}
                        </li>
                    </ul>
            </div>
        </div>
        <div class="prod-cont">
            <div class="prod-rating-wrap">
                <p data-rating="4" class="prod-rating">
                    <i class="rating-ico" title="1"></i>
                    <i class="rating-ico" title="2"></i>
                    <i class="rating-ico" title="3"></i>
                    <i class="rating-ico" title="4"></i>
                    <i class="rating-ico" title="5"></i>
                </p>
                <p class="prod-rating-count">7</p>
            </div>
            <p class="prod-categs"><a href="#">{{product.category}}</a></p>
            <h1>${{product.name}}</h1>
            <div class="variations_form cart">
                <p class="prod-price">${{product.price}}</p>
                <p class="prod-excerpt">${{product.description}}... 
                    <a id="prod-showdesc" class="prod-excerpt-more" href="#">read more</a></p>
                <div class="prod-add">
                    <p>fffffffffffffffffffffffffffffffffff</p>
                    <p>fffffffffffffffffffffffffffffffffff</p>
                    <p>fffffffffffffffffffffffffffffffffff</p>
                    <p>fffffffffffffffffffffffffffffffffff</p>
                    <p>fffffffffffffffffffffffffffffffffff</p>
                    <p>fffffffffffffffffffffffffffffffffff</p>
                    <p>fffffffffffffffffffffffffffffffffff</p>
                    <p>fffffffffffffffffffffffffffffffffff</p>
                    <p>fffffffffffffffffffffffffffffffffff</p>
                    <p>fffffffffffffffffffffffffffffffffff</p>
                    <form action="{% url "web:addToCar" product.id %}" method="post">
                        {% csrf_token %}
                        <div class="variations">
                            <div class="variations-row">
                                <div class="label"><label >Color</label></div>
                                <div class="value">
                                    <select>
                                        <option value="">Choose an option</option>
                                        <option value="blue">Blue</option>
                                        <option value="green">Green</option>
                                        <option value="yellow">Yellow</option>
                                    </select>
                                </div>
                            </div>
                        </div>  
                        <div>
                            <button type="submit" class="button"><i class="icon ion-android-cart"></i> Agregar al Carrito</button>
                            <p class="qnt-wrap prod-li-qnt">
                                <a href="#" class="qnt-plus prod-li-plus"><i class="icon ion-arrow-up-b"></i></a>
                                <input type="text" name="cuantity" value="1">
                                <a href="#" class="qnt-minus prod-li-minus"><i class="icon ion-arrow-down-b"></i></a>
                            </p>
                        </div>
                    </form>
                </div>
            </div>
            <div class="prod-props">
                <dl class="product_meta">                    
                </dl>
            </div>
        </div>
    </div>
    </article>

{% endblock  %}