myEcommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("",include("web.urls")),
    path('admin/', admin.site.urls),
    path('paypal/', include("paypal.standard.ipn.urls")),

] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/urls.py
from django.urls import path
from . import views

app_name = "web"
urlpatterns = [
    path('',views.index, name="index"),
    path("productsByCategory/<int:category_id>", views.productsByCategory, name="productsByCategory"),
    path("productsByName", views.productsByName, name="productsByName"),
    path("product/<int:product_id>", views.productDetail, name="product"),
    path("car", views.car, name="car"),
    path("addToCar/<int:product_id>", views.addToCar, name="addToCar"),
    path("deleteProductToCar/<int:product_id>", views.deleteProductToCar, name="deleteProductToCar"),
    path("clearCar", views.clearCar, name="clearCar"),
    path("createUser", views.createUser, name="createUser") ,
    path("acount", views.userAcount, name="acount"),
    path("updateClient", views.updateClient, name="updateClient"),
    path("login", views.loginUser, name="loginUser"),
    path("logout", views.logoutUser, name="logoutUser"),
    path("registerOrder", views.registerOrder, name="registerOrder"),
    path("confirmOrder", views.confirmOrder, name="confirmOrder"),
    path("thanks", views.thanks, name="thanks")
]

web/models.py
from django.db import models

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=200)
    registration_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
    

class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.RESTRICT)
    name = models.CharField(max_length=200)
    description = models.TextField(null=True)
    price = models.DecimalField(max_digits=9, decimal_places=2)
    registration_date = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to="products", blank=True)

    def __str__(self):
        return self.name
    

from django.contrib.auth.models import User

class Client(models.Model): 
    user = models.OneToOneField(User, on_delete=models.RESTRICT)
    dni = models.CharField(max_length=10)
    gender = models.CharField(max_length=1, default="M")
    phone = models.CharField(max_length=20)
    birthdate = models.DateField(null=True)
    address = models.TextField() 

    def __str__(self):
        return self.dni


class Order(models.Model):

    state_choices = (
        ("0", "required"),
        ("1", "paid")
    )

    client = models.ForeignKey(Client, on_delete=models.RESTRICT)
    singup_date = models.DateTimeField(auto_now_add=True)
    number_order= models.CharField(max_length=20, null=True)
    total = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    state = models.CharField(max_length=1, default="0", choices= state_choices)


    def __str__(self):
        return self.number_order
    

class DetailOrder(models.Model):
    order = models.ForeignKey(Order, on_delete=models.RESTRICT)
    product = models.ForeignKey(Product, on_delete=models.RESTRICT)
    cuantity = models.IntegerField(default=1)
    subtotal = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.product.name

web/templates/includes/catalogo/catalogo.html
<div class="row prod-items prod-items-2">
    {% for product in products %}
    <article class="cf-sm-6 cf-md-6 cf-lg-6 col-xs-6 col-sm-6 col-md-6 col-lg-6 sectgl-item">
        <div class="sectgl prod-i">
            <div class="prod-i-top">
                <a class="prod-i-img" href="{% url "web:product" product.id %}">
                    {% if product.image %}
                        <img src="" alt="">
                    {% else %}
                        <img src="https://via.placeholder.com/250" alt="">
                    {% endif %}
                </a>
                <div class="prod-i-actions">
                    <div class="prod-i-actions-in">
                        <p class="prod-i-cart">
                            <a href="{% url "web:addToCar" product.id %}" class="hover-label prod-addbtn"><i class="icon ion-android-cart"></i><span>Añadir al carrito</span></a>
                        </p>
                    </div>
                </div>
            </div>
            <div class="prod-i-bot">
                <div class="prod-i-info">
                    <p class="prod-i-price">${{product.price}}</p>
                    <p class="prod-i-categ"><a href="#">{{product.category}}</a></p>
                </div>
                <h3 class="prod-i-ttl"><a href="{% url "web:product" product.id %}">{{product.name}}</a></h3>
            </div>
        </div>
    </article>
    {% endfor %}
</div>

web/templates/includes/catalogo/categorias.html
<div class="blog-sb-widget multishopcategories_widget">
    <h3 class="widgettitle">Categorias</h3>
    <div class="section-sb-current">
        <ul class="section-sb-list">
            {% for category in categories %}
            <li>
               <a href="{% url 'web:productsByCategory' category.id %}">
                    <span class="section-sb-label">{{category.name}} 
                       <span class="count">{{category.product_set.all.count}}</span>
                    </span>
                </a>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>